### ISSUE TITLE
required: false not working as expected?

### ISSUE THREAD

**Issue by wshin93** [CharlGottschalk/approvejs#10]
Hello,

I have an optional field in my form where the user is not required to provide a value, but if there is a value it must be within a certain range.

I tried to do this
`var result = approve.value('', {required: false, range: {min: 3, max: 10})`

But the result keep saying it "is required". I thought required: false would skip the remaining rules if the value is not provided.

Is is possible to achieve what I want using this library?

Thank you.

**Comment by CharlGottschalk** [comment]
Hi @wshin93 

Yes, you can do that absolutely.
Simply remove the required rule i.e.:

```javascript
var result = approve.value('', {range: {min: 3, max: 10});
```

If a boolean rule is present, it will be tested regardless of its constraint.
So for example, the `required` rule will be tested whether you set it to `true`, `false`, `1` or even `'run me'`.
