### ISSUE TITLE
tests#format expects the regex parameter

### ISSUE THREAD

**Issue by tjmcewan** [CharlGottschalk/approvejs#11]
Howdy, following [the example given for the format test](http://charlgottschalk.co.za/projects/approvejs/docs/3.0.0/tests#format), I get the error `format expects the regex parameter`.  I'm guessing it just needs an update, as the following works fine:

```
var rule = {
    format: {
        regex: /^[A-Za-z]+$/
    }
};
```

Thanks!

**Comment by CharlGottschalk** [comment]
Hi @tjmcewan 

Thanks for letting me know.
I fixed the issue in [v3.0.2](https://github.com/CharlGottschalk/approvejs/releases/tag/v3.0.2)
