### ISSUE TITLE
Null values failing string validation rules such as 'max'

### ISSUE THREAD

**Issue by neutralrockets** [CharlGottschalk/approvejs#12]
Hi,

Not sure if this is expected behaviour but when I validate against null values, tests such as "max" fail.

For example if I validate an address, which has an optional address line 2 (null in the database) and give it a max:255 rule, it will fail the test and return "the field must be max 255 characters" (when it is clearly empty/null).

I would still like to validate the field if there happens to be something there, but also somehow treat null strings as empty when it comes to these tests? Any suggestions?

**Comment by CharlGottschalk** [comment]
Hi @neutralrockets

Thanks for bringing this to my attention.

Apologies for the delay in response. 

Ideally, I think, a flag might be appropriate to tell a test to ignore null values. 

I'll fix the issue and respond A.S.A.P.

**Comment by CharlGottschalk** [comment]
Added `ignoreNull` property for handling `null` values.

Usage:

**Test will pass**

```javascript
var rules = {
    required: true,
    email: true,
    ignoreNull: true
};

var result = approve.value(null, rules);
```

**Test will fail**

```javascript
var rules = {
    required: true,
    email: true
};

var result = approve.value(null, rules);
```
