### ISSUE TITLE
Doc page fell over - nice work on the script, Thanks for the efforts to date!

### ISSUE THREAD

**Issue by jondo89** [CharlGottschalk/approvejs#18]
404
There isn't a GitHub Pages site here.

Did you mean to visit CharlGottschalk.github.io? Please note that this site belongs to a GitHub user and is not an official GitHub site.

If you're the owner of this site, please update your links to use CharlGottschalk.github.io instead. Subdomains of github.com are deprecated for GitHub Pages. They will not redirect to github.io after April 15, 2021.

Contact Support — GitHub Status — @githubstatus

**Comment by CharlGottschalk** [comment]
Thanks for the compliment @jondo89 
Apologies for the late response, life took over.

I fixed the docs urls. If you still get the same error, please CTRL+F5 on your browser.
