### ISSUE TITLE
Only show errors that are relevant

### ISSUE THREAD

**Issue by flamerohr** [CharlGottschalk/approvejs#8]
Hi, I like what has been built so far.

I had a blocker while using this module where the validation would return error messages for all validation, rather than only the messages that failed.
To get around that, I would've had to loop through each rule individually, which kind of defeated the purpose of listing all the rules for the Validation engine.

Would there be a config available to show all or only those that apply?

**Comment by CharlGottschalk** [comment]
Hi @flamerohr 

If I understand correctly, you would pass an object containing various rules that need to be tested i.e.

```javascript
var rules = {
    title: 'Email',
    email: true,
    required: true
};
```

and then upon testing a value that failed both the `required` and `email` tests, the result included errors for both rules i.e.

```
'Email must be a valid email address'
'Email is required'
```

but you don't want both errors returned, you want for instance, only the `required` test's error returned, and only once a value passes the `required` test, then the `email` test is performed and it's error returned if it fails?

Am I understanding correctly?

**Comment by flamerohr** [comment]
Yes, that's correct :) optionality for the non-required rules is important for my usecase, as we have UX as a main focus.

**Comment by CharlGottschalk** [comment]
Ok, I'll try and get that sorted by the end of my day. @flamerohr

**Comment by CharlGottschalk** [comment]
Added `stop` property to cancel any further testing after each first failed test.

More info at [docs](http://charlgottschalk.co.za/projects/approvejs/docs/2.1.0/configuration).

**Comment by flamerohr** [comment]
Thanks, that's great :)

I would like to point out something about this note:
> Note that rules are tested in the order in which they appear in the rule object
The V8 javascript engine does not guarantee object property order, so it's possible that "required" can move to the bottom of the "order" without warning.

**Comment by CharlGottschalk** [comment]
@flamerohr That's true.

Ok, I'll have to look at a way of providing ordering.

**Comment by oshihirii** [comment]
Hello,

I have come across what I think is a related issue - the order of `required` in the `rules` object sometimes causes it not to be applied (or to be applied and then not "un-applied")?

Just started looking into `approve` today and have not written validation scripts before so just playing around on this [codepen](https://codepen.io/oshihirii/pen/ZJvvdp).

Is that expected behaviour?

Thank You.
